### ISSUE TITLE
benchmarks

### ISSUE THREAD

**Issue by davidmarkclements** [IndigoUnited/pino-err-serializer#1]
Hey @satazor this is awesome!

I'd love to see some benchmarks to determine the overhead vs core error serializer

**Comment by satazor** [comment]
Hi @davidmarkclements,

I created this for npms.io. We attach additional props to err for context, but these were never logged with the core error serializer.

Regarding benchmarks, what do you suggest to use?

**Comment by satazor** [comment]
I've added some benchmarks to the `bench` branch, here's the output:

<img width="424" alt="screen shot 2016-11-27 at 9 51 16 pm" src="https://cloud.githubusercontent.com/assets/1017236/20652152/b48209b4-b4eb-11e6-848f-f3ca43500fff.png">


I find a bit strange that this serializer is slightly faster when serializing a simple error compared to the standard one. Still, what you think about the results?

**Comment by satazor** [comment]
I think the issue here is the v8 optimizing code as it runs.. the first function being bench is always slower.

**Comment by satazor** [comment]
After adding some warming up iterations, here are the results (ignore the warmup):

<img width="478" alt="screen shot 2016-11-27 at 10 01 57 pm" src="https://cloud.githubusercontent.com/assets/1017236/20652231/32874378-b4ed-11e6-9b76-7b3ff29ec902.png">

For simple errors, there's real no difference. For error with additional properties, there's a small difference. At the moment I'm using `lodash.assignwith` which gets called for each property to be called. We can replace it with a normal `for` loop to increase performance.

**Comment by davidmarkclements** [comment]
so what we do for benchmarks is run them twice and take an average (non-warmed up is still relevant I think)

easy way to to this is to pass the result of fastbench back into itself
https://github.com/pinojs/pino/blob/master/benchmarks/basic.bench.js#L82

for you it would be `runBench(runBench)`

Even at that a diff of 8ms is negligible - that can be caused by a vast number of confounding variables - so really we're looking for diffs in the +20ms range 

this looks really good! 

cc @mcollina @jsumners

**Comment by satazor** [comment]
@davidmarkclements I see, still since V8 is optimizing hot code (specifically the Pino prototype methods) and those methods are shared by all of the iterations, the first ones will have higher times. Even if we run the suite twice, this is unfair for the first iterations of all.

I will upgrade the code to call it twice though.

**Comment by davidmarkclements** [comment]
you're right - but it's equally unfair - the comparison between the two things is constant (two separate instances of pino)

**Comment by satazor** [comment]
Here are the results:

<img width="649" alt="screen shot 2016-11-27 at 10 38 29 pm" src="https://cloud.githubusercontent.com/assets/1017236/20652488/3fb006ac-b4f2-11e6-9441-775cb9524bd8.png">

As you can see, the first bench is slower compared to the custom err serializer; but if I switch the order then the custom err serializer is slower. That's why I said it's unfair for the first iterations :p

**Comment by satazor** [comment]
> you're right - but it's equally unfair - the comparison between the two things is constant (two separate instances of pino)

They are two instances, but they share the same pino prototype methods.. v8 optimizes those in the first few runs, that's why it's unfair.

**Comment by davidmarkclements** [comment]
oh yah that's true - you could do

```js
const loggerStdSerializer = require('pino')({ serializers: { err: pino.stdSerializers.err } }, process.stderr);
delete require.cache(require.resolve('pino'))
const loggerCustomSerializer = require('pino')({ serializers: { err: errSerializer } }, process.stderr);
```

**Comment by satazor** [comment]
@davidmarkclements Clever idea. I've tried but the results are similar. I guess v8 is doing some trickery to identify similar cached stuff.

**Comment by davidmarkclements** [comment]
yeah, from what I understand, I think v8 does things with "shapes"

at any rate the benchmarks are close which is awesome

regarding the for loop instead of `lodash.assignWith` - I'm not sure how much more perf you'll squeeze out. Maybe worth it to be zero-dep though. 

@mcollina what do you think to just requiring this into pino core as the default err serializer?

**Comment by satazor** [comment]
I've improved the bench by making the `complexErr` more complex with a lot of properties.

With `lodash.assignwith`:

<img width="377" alt="screen shot 2016-11-27 at 11 03 02 pm" src="https://cloud.githubusercontent.com/assets/1017236/20652683/ad6c3866-b4f5-11e6-9110-0fd09607ded4.png">


Without `lodash.assignwith`:

<img width="410" alt="screen shot 2016-11-27 at 11 01 59 pm" src="https://cloud.githubusercontent.com/assets/1017236/20652680/a327601a-b4f5-11e6-8c2a-712270e6665b.png">

**Comment by davidmarkclements** [comment]
yeah I think if you make the complexErr even larger more complex it'll expose a bigger gap, for those cases for loop would be best for sure

**Comment by satazor** [comment]
Yep that was exactly what I thought, hehe :)

**Comment by jsumners** [comment]
Everything looks great to me. Especially is lodash is dropped. I have a personal aversion to including a dependency when it's very simple to just write the code inline.

**Comment by satazor** [comment]
The version without lodash is available in https://github.com/IndigoUnited/pino-err-serializer/blob/bench-optimized/index.js#L3

**Comment by mcollina** [comment]
I think using this as the default error serializer makes a lot of sense. Not sure if we can adopt it for bare Error objects, but it's worth a spin.

Anyway, would you like to join the pino org and move this over there?

**Comment by satazor** [comment]
@mcollina Sure, that will be a pleasure :)

**Comment by mcollina** [comment]
@satazor what would you prefer, maintain this as its own module, or send a PR to pino and integrate it directly. 

@davidmarkclements @jsumners what do you think?

**Comment by davidmarkclements** [comment]
I'm happy with either - up to @satazor

**Comment by satazor** [comment]
@mcollina I have no problems with deprecating this and add it to the core. The changes are quite minimal.

**Comment by satazor** [comment]
@mcollina I've been added to the org but I can't push to pinojs/pino. I wanted to create a new branch and make a PR. Will you give me publish rights or shall I do a standard PR by forking?

**Comment by satazor** [comment]
Closing since this is part of pino!
